language: "perl"

perl:
  - "5.14"

sudo: false

addons:
  apt:
    packages:
    - unzip

env:
  - COVERALLS=false

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - wget http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz
    - mkdir bioperl-live && tar zxvf BioPerl-1.6.1.tar.gz -C bioperl-live --strip-components 1
    - git clone --branch master --depth 1 https://github.com/samtools/tabix.git
    - cd tabix
    - make
    - cd perl
    - perl Makefile.PL
    - make && make install
    - cd ../../
    - cd ensembl-variation/C_code/
    - make
    - cd ../../
    - git clone --branch master --depth 1 https://github.com/samtools/htslib.git
    - cd htslib
    - make
    - export HTSLIB_DIR=$(pwd -P)
    - cd ../
    - git clone --branch master --depth 1 https://github.com/Ensembl/Bio-HTS
    - cd Bio-HTS
    - perl Build.PL --htslib $HTSLIB_DIR
    - ./Build
    - cd ../

install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm -v --installdeps --with-recommends --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp travisci/MultiTestDB.conf.travisci t/MultiTestDB.conf

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
